'use strict';
const { SlashCommandBuilder, PermissionFlagsBits, ChannelType } = require('discord.js');
const admin = PermissionFlagsBits.ManageGuild;
module.exports = [
  new SlashCommandBuilder().setName('setup').setDescription('ผู้ดูแล: ตั้งค่าห้องรายงาน บทบาทสมาชิก และเวลาสรุป')
    .setDefaultMemberPermissions(admin)
    .addChannelOption(o => o.setName('attendance').setDescription('ห้องเช็กชื่อ').addChannelTypes(ChannelType.GuildText).setRequired(true))
    .addChannelOption(o => o.setName('inventory').setDescription('ห้องเช็กของ').addChannelTypes(ChannelType.GuildText).setRequired(true))
    .addRoleOption(o => o.setName('role').setDescription('บทบาทสมาชิกที่ต้องเช็กชื่อ').setRequired(true))
    .addStringOption(o => o.setName('time').setDescription('เวลาสรุปและเริ่มนับสาย เช่น 20:00').setRequired(false))
    .addChannelOption(o => o.setName('delivery').setDescription('ห้องส่งของใหม่ (ไม่บังคับ ถ้าตั้งไว้แล้ว)').addChannelTypes(ChannelType.GuildText)),
  new SlashCommandBuilder().setName('panel').setDescription('ผู้ดูแล: ส่งแผงปุ่มกดเช็กชื่อหรือเช็กของ')
    .setDefaultMemberPermissions(admin)
    .addStringOption(o => o.setName('type').setDescription('ประเภทแผงปุ่ม').setRequired(true)
      .addChoices({ name: 'เช็กชื่อ', value: 'attendance' }, { name: 'เช็กของ', value: 'inventory' })),
  new SlashCommandBuilder().setName('checkin').setDescription('เช็กชื่อวันนี้ด้วยบัญชี Discord ของตนเอง')
    .addStringOption(o => o.setName('status').setDescription('สถานะ').setRequired(true)
      .addChoices({ name: 'มา', value: 'present' }, { name: 'มาสาย', value: 'late' }, { name: 'ลา', value: 'leave' }))
    .addStringOption(o => o.setName('reason').setDescription('เหตุผลกรณีมาสายหรือลา (ถ้าไม่ใส่ จะมีช่องให้กรอก)').setMaxLength(250))
    .addStringOption(o => o.setName('start').setDescription('เฉพาะลา: วันแรก เช่น 22/09/2569 หรือ 2026-09-22'))
    .addStringOption(o => o.setName('end').setDescription('เฉพาะลา: วันสุดท้าย เว้นว่างคือวันแรก')),
  new SlashCommandBuilder().setName('leave').setDescription('แจ้งลาวันเดียวหรือหลายวัน พร้อมเหตุผล (ลาได้ทั้งวัน)')
    .addStringOption(o => o.setName('start').setDescription('วันเริ่มลา เช่น 26/09/2569 หรือ 2026-09-26').setRequired(true))
    .addStringOption(o => o.setName('reason').setDescription('เหตุผลการลา (3–250 ตัวอักษร)').setRequired(true).setMinLength(3).setMaxLength(250))
    .addStringOption(o => o.setName('end').setDescription('วันสุดท้าย เว้นว่างคือวันแรก')),
  new SlashCommandBuilder().setName('history').setDescription('ดูประวัติเช็กชื่อ ส่งในห้อง 5 นาทีแล้วลบอัตโนมัติ')
    .addUserOption(o => o.setName('member').setDescription('สมาชิกที่ต้องการดู ไม่เลือกคือดูตนเอง')),
  new SlashCommandBuilder().setName('item').setDescription('ผู้ดูแล: จัดการรายการของที่ต้องตรวจ')
    .setDefaultMemberPermissions(admin)
    .addSubcommand(s => s.setName('add').setDescription('เพิ่มของที่ต้องตรวจ')
      .addStringOption(o => o.setName('name').setDescription('ชื่อของ').setRequired(true).setMaxLength(80))
      .addIntegerOption(o => o.setName('quantity').setDescription('จำนวนที่ควรมีต่อสมาชิก').setRequired(true).setMinValue(0).setMaxValue(1000000)))
    .addSubcommand(s => s.setName('remove').setDescription('ลบรายการของ (ประวัติเดิมยังอยู่)')
      .addStringOption(o => o.setName('name').setDescription('เลือกรายการ').setRequired(true).setAutocomplete(true)))
    .addSubcommand(s => s.setName('list').setDescription('แสดงรายการของทั้งหมด')),
  new SlashCommandBuilder().setName('checkitem').setDescription('ตรวจของรายวัน โดยอ้างอิงบัญชี Discord ของคุณ')
    .addStringOption(o => o.setName('name').setDescription('รายการของ').setRequired(true).setAutocomplete(true))
    .addIntegerOption(o => o.setName('found').setDescription('จำนวนที่ตรวจพบ').setRequired(true).setMinValue(0).setMaxValue(1000000))
    .addStringOption(o => o.setName('condition').setDescription('สภาพของ').setRequired(true)
      .addChoices({ name: 'ปกติ', value: 'normal' }, { name: 'ชำรุด', value: 'damaged' }, { name: 'สูญหาย', value: 'lost' }))
    .addStringOption(o => o.setName('note').setDescription('หมายเหตุ (ถ้ามี)').setMaxLength(250)),
  new SlashCommandBuilder().setName('delivery').setDescription('ระบบห้องส่งของ [IMT] IMMORTAL')
    .addSubcommand(s => s.setName('setchannel').setDescription('ผู้ดูแล: กำหนดห้องส่งของ')
      .addChannelOption(o => o.setName('channel').setDescription('ห้อง #ส่งของ').addChannelTypes(ChannelType.GuildText).setRequired(true)))
    .addSubcommand(s => s.setName('panel').setDescription('ผู้ดูแล: สร้าง UI ส่งของแบบปุ่ม'))
    .addSubcommand(s => s.setName('send').setDescription('สมาชิก: แจ้งส่งของ ต้องยืนยันก่อนบันทึก')
      .addStringOption(o => o.setName('name').setDescription('ชื่อของ เช่น red money หรือ weapon box').setRequired(true).setMaxLength(80))
      .addIntegerOption(o => o.setName('quantity').setDescription('จำนวนที่ส่ง เช่น 100').setRequired(true).setMinValue(1).setMaxValue(1000000000000))
      .addStringOption(o => o.setName('unit').setDescription('หน่วย เช่น ชิ้น หรือ บาท').setMaxLength(20)))
    .addSubcommand(s => s.setName('report').setDescription('ดูรายงานส่งของวันนี้'))
    .addSubcommand(s => s.setName('history').setDescription('ดูประวัติส่งของล่าสุด')
      .addUserOption(o => o.setName('member').setDescription('กรองตามสมาชิก ผู้ส่ง/ผู้จัดการ'))
      .addStringOption(o => o.setName('item').setDescription('กรองตามชื่อของ'))
      .addStringOption(o => o.setName('date').setDescription('กรองวันที่ YYYY-MM-DD'))
      .addIntegerOption(o => o.setName('limit').setDescription('จำนวนรายการ 1–25').setMinValue(1).setMaxValue(25)))
    .addSubcommandGroup(g => g.setName('role').setDescription('กำหนดยศที่สามารถแก้ไข/ยืนยันระบบส่งของได้')
      .addSubcommand(s => s.setName('add').setDescription('เพิ่มยศผู้จัดการส่งของ')
        .addRoleOption(o => o.setName('role').setDescription('ยศที่สามารถแก้ไข/ยืนยันของส่ง').setRequired(true)))
      .addSubcommand(s => s.setName('remove').setDescription('ลบยศผู้จัดการส่งของ')
        .addRoleOption(o => o.setName('role').setDescription('ยศที่ต้องการลบ').setRequired(true)))
      .addSubcommand(s => s.setName('list').setDescription('ดูยศผู้จัดการส่งของ')))
    .addSubcommandGroup(g => g.setName('item').setDescription('จัดการรายการของที่ต้องส่ง')
      .addSubcommand(s => s.setName('add').setDescription('สร้างหรือแก้ไขของที่ต้องส่ง')
        .addStringOption(o => o.setName('name').setDescription('ชื่อของ').setRequired(true).setMaxLength(80))
        .addIntegerOption(o => o.setName('quantity').setDescription('จำนวนที่ต้องส่ง').setRequired(true).setMinValue(0).setMaxValue(1000000000000))
        .addStringOption(o => o.setName('unit').setDescription('หน่วย เช่น ชิ้น หรือ บาท').setMaxLength(20)))
      .addSubcommand(s => s.setName('remove').setDescription('ลบของที่ต้องส่ง')
        .addStringOption(o => o.setName('name').setDescription('ชื่อของ').setRequired(true).setMaxLength(80)))
      .addSubcommand(s => s.setName('list').setDescription('ตรวจสอบของที่ต้องส่ง'))),
  new SlashCommandBuilder().setName('locker').setDescription('ผู้ดูแล: จัดการตู้แก๊งส่วนกลาง')
    .setDefaultMemberPermissions(admin)
    .addSubcommand(s => s.setName('panel').setDescription('สร้าง Dashboard ตู้แก๊งพร้อมปุ่มจัดการ'))
    .addSubcommand(s => s.setName('add').setDescription('เพิ่มจำนวนเข้าตู้แก๊ง ถ้ามีของอยู่แล้วจะบวกยอดให้')
      .addStringOption(o => o.setName('name').setDescription('ชื่อของ').setRequired(true).setMaxLength(80))
      .addIntegerOption(o => o.setName('quantity').setDescription('จำนวนที่เพิ่ม').setRequired(true).setMinValue(1))
      .addStringOption(o => o.setName('unit').setDescription('หน่วย เช่น ชิ้น หรือ บาท')))
    .addSubcommand(s => s.setName('edit').setDescription('ตั้งจำนวนใหม่/แก้ชื่อ/แก้หน่วยของตู้แก๊ง')
      .addStringOption(o => o.setName('name').setDescription('ชื่อของเดิม').setRequired(true))
      .addIntegerOption(o => o.setName('quantity').setDescription('จำนวนใหม่').setRequired(true).setMinValue(0))
      .addStringOption(o => o.setName('unit').setDescription('หน่วยใหม่ (ไม่บังคับ)'))
      .addStringOption(o => o.setName('newname').setDescription('เปลี่ยนชื่อรายการใหม่ (ไม่บังคับ)').setMaxLength(80)))
    .addSubcommand(s => s.setName('remove').setDescription('ลดจำนวนบางส่วน หรือลบรายการจากตู้แก๊ง')
      .addStringOption(o => o.setName('name').setDescription('ชื่อของ').setRequired(true))
      .addIntegerOption(o => o.setName('quantity').setDescription('จำนวนที่ต้องการลด ถ้าไม่ใส่จะลบทั้งรายการ').setMinValue(1)))
    .addSubcommand(s => s.setName('list').setDescription('ดูตู้แก๊งส่วนกลาง'))
    .addSubcommandGroup(g => g.setName('role').setDescription('ตั้งยศที่แก้ไขตู้แก๊งได้')
      .addSubcommand(s => s.setName('add').setDescription('เพิ่มยศผู้จัดการตู้แก๊ง')
        .addRoleOption(o => o.setName('role').setDescription('ยศที่ให้แก้ไขตู้แก๊งได้').setRequired(true)))
      .addSubcommand(s => s.setName('remove').setDescription('ลบยศผู้จัดการตู้แก๊ง')
        .addRoleOption(o => o.setName('role').setDescription('ยศที่จะลบสิทธิ์').setRequired(true)))
      .addSubcommand(s => s.setName('list').setDescription('ดูยศที่สามารถแก้ไขตู้แก๊ง'))),

  new SlashCommandBuilder().setName('house').setDescription('ระบบเช็กชื่อตามบ้าน แยกจากเช็กชื่อปกติ')
    .addSubcommand(s => s.setName('panel').setDescription('ผู้ดูแล: สร้างแผงเช็กชื่อตามบ้าน')
      .addChannelOption(o => o.setName('channel').setDescription('ห้องที่จะส่งแผงบ้าน ถ้าไม่เลือกใช้ห้องเช็กชื่อ').addChannelTypes(ChannelType.GuildText)))
    .addSubcommand(s => s.setName('add').setDescription('ผู้ดูแล: เพิ่มบ้าน')
      .addStringOption(o => o.setName('name').setDescription('ชื่อบ้าน เช่น บ้าน 1').setRequired(true).setMaxLength(50)))
    .addSubcommand(s => s.setName('remove').setDescription('ผู้ดูแล: ลบบ้าน')
      .addStringOption(o => o.setName('name').setDescription('ชื่อบ้าน').setRequired(true).setMaxLength(50)))
    .addSubcommand(s => s.setName('list').setDescription('ดูรายชื่อบ้านและสมาชิก'))
    .addSubcommandGroup(g => g.setName('leader').setDescription('ตั้งค่าหัวหน้าบ้าน')
      .addSubcommand(s => s.setName('set').setDescription('ผู้ดูแล: ตั้งหัวหน้าบ้าน')
        .addStringOption(o => o.setName('house').setDescription('ชื่อบ้าน').setRequired(true).setMaxLength(50))
        .addUserOption(o => o.setName('user').setDescription('หัวหน้าบ้าน').setRequired(true))))
    .addSubcommandGroup(g => g.setName('member').setDescription('จัดการลูกบ้าน')
      .addSubcommand(s => s.setName('add').setDescription('ผู้ดูแล: เพิ่ม/ย้ายสมาชิกเข้าบ้าน')
        .addStringOption(o => o.setName('house').setDescription('ชื่อบ้าน').setRequired(true).setMaxLength(50))
        .addUserOption(o => o.setName('user').setDescription('ลูกบ้าน').setRequired(true)))
      .addSubcommand(s => s.setName('remove').setDescription('ผู้ดูแล: เอาสมาชิกออกจากบ้าน')
        .addStringOption(o => o.setName('house').setDescription('ชื่อบ้าน').setRequired(true).setMaxLength(50))
        .addUserOption(o => o.setName('user').setDescription('ลูกบ้าน').setRequired(true)))),
  new SlashCommandBuilder().setName('status').setDescription('ดูสถานะเช็กชื่อและเช็กของวันนี้ของตนเอง'),
  new SlashCommandBuilder().setName('report').setDescription('ผู้ดูแล: ดูสรุปของวันนี้')
    .setDefaultMemberPermissions(admin)
].map(c => c.toJSON());
